/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package janken;

public interface Hand {

    /**
    手の強弱を比較する。
    返り値 -1 : 自身が引数で指定した手より弱い
    　　　　0 : 自身が引数で指定した手と同じ
    　　　　1 : 自身が引数で指定した手より強い
     */
    public int compare(Hand hand);
    public String getHandName();
}
