/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package janken;

public class Pa implements Hand {
    private String HAND_NAME = "パー";

    public int compare(Hand hand) {
        //TODO:例外の処理

        if(hand instanceof Gu) {
            return 1;
        } else if(hand instanceof Choki) {
            return -1;
        } else {
            return 0;
        }
    }

    public String getHandName() {
        return this.HAND_NAME;
    }
}