/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package janken;

import java.util.Random;

public class Player {
    private String playerName;
    private Hand hand;

    public Player(String playerName) {
        this.playerName = playerName;
    }

    public void createRandomHand() {
        //TODO:実装する
        Random random = new Random();
        int randomValue = random.nextInt(3);

        if(randomValue == 0) {
            this.hand = new Gu();
        } else if(randomValue == 1) {
            this.hand = new Choki();
        } else {
            this.hand = new Pa();
        }
    }

    public String getPlayerName() {
        return this.playerName;
    }

    public void setPlayerName(String name) {
        this.playerName = name;
    }

    public Hand getHand() {
        return this.hand;
    }

    public void setHand(Hand hand) {
        this.hand = hand;
    }
}
