/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ticket;

import org.junit.Test;
import static org.junit.Assert.*;

public class CartTest {
    @Test public void testGetTotalPrice() {
        Cart cart = new Cart();
        cart.addItem(new Item(1, "test", 100));
        cart.addItem(new Item(1, "test", 100));
        cart.addItem(new Item(2, "test2", 300));
        
        assertEquals(500, cart.getTotalPrice());
    }
}
